package com.xxs.json.entity;

import lombok.*;

import java.io.Serializable;
import java.util.Date;
@Data
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class BaseConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.config_group
     *
     * @mbggenerated
     */
    private String configGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.config_name
     *
     * @mbggenerated
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.config_body
     *
     * @mbggenerated
     */
    private String configBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.env
     *
     * @mbggenerated
     */
    private String env;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_config.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.id
     *
     * @return the value of base_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.id
     *
     * @param id the value for base_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.gmt_create
     *
     * @return the value of base_config.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.gmt_create
     *
     * @param gmtCreate the value for base_config.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.gmt_modified
     *
     * @return the value of base_config.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.gmt_modified
     *
     * @param gmtModified the value for base_config.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.config_group
     *
     * @return the value of base_config.config_group
     *
     * @mbggenerated
     */
    public String getConfigGroup() {
        return configGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.config_group
     *
     * @param configGroup the value for base_config.config_group
     *
     * @mbggenerated
     */
    public void setConfigGroup(String configGroup) {
        this.configGroup = configGroup == null ? null : configGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.config_name
     *
     * @return the value of base_config.config_name
     *
     * @mbggenerated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.config_name
     *
     * @param configName the value for base_config.config_name
     *
     * @mbggenerated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.config_body
     *
     * @return the value of base_config.config_body
     *
     * @mbggenerated
     */
    public String getConfigBody() {
        return configBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.config_body
     *
     * @param configBody the value for base_config.config_body
     *
     * @mbggenerated
     */
    public void setConfigBody(String configBody) {
        this.configBody = configBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.remark
     *
     * @return the value of base_config.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.remark
     *
     * @param remark the value for base_config.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.env
     *
     * @return the value of base_config.env
     *
     * @mbggenerated
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.env
     *
     * @param env the value for base_config.env
     *
     * @mbggenerated
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_config.is_deleted
     *
     * @return the value of base_config.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_config.is_deleted
     *
     * @param isDeleted the value for base_config.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}