package com.xxs.json.entity;

import lombok.*;

import java.io.Serializable;
import java.util.Date;
@Data
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class RequestLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.request_name
     *
     * @mbggenerated
     */
    private String requestName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.request_body
     *
     * @mbggenerated
     */
    private String requestBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table request_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.id
     *
     * @return the value of request_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.id
     *
     * @param id the value for request_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.gmt_create
     *
     * @return the value of request_log.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.gmt_create
     *
     * @param gmtCreate the value for request_log.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.gmt_modified
     *
     * @return the value of request_log.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.gmt_modified
     *
     * @param gmtModified the value for request_log.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.status
     *
     * @return the value of request_log.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.status
     *
     * @param status the value for request_log.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.request_name
     *
     * @return the value of request_log.request_name
     *
     * @mbggenerated
     */
    public String getRequestName() {
        return requestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.request_name
     *
     * @param requestName the value for request_log.request_name
     *
     * @mbggenerated
     */
    public void setRequestName(String requestName) {
        this.requestName = requestName == null ? null : requestName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.is_deleted
     *
     * @return the value of request_log.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.is_deleted
     *
     * @param isDeleted the value for request_log.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.request_body
     *
     * @return the value of request_log.request_body
     *
     * @mbggenerated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.request_body
     *
     * @param requestBody the value for request_log.request_body
     *
     * @mbggenerated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.remark
     *
     * @return the value of request_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.remark
     *
     * @param remark the value for request_log.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}