package com.xxs.json.entity;

import lombok.*;

import java.io.Serializable;
import java.util.Date;
@Data
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class TextTag implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_tag.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_tag.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_tag.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_tag.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_tag.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_tag.text_id_list
     *
     * @mbggenerated
     */
    private String textIdList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_tag.env
     *
     * @mbggenerated
     */
    private String env;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table text_tag
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_tag.id
     *
     * @return the value of text_tag.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_tag.id
     *
     * @param id the value for text_tag.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_tag.gmt_create
     *
     * @return the value of text_tag.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_tag.gmt_create
     *
     * @param gmtCreate the value for text_tag.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_tag.gmt_modified
     *
     * @return the value of text_tag.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_tag.gmt_modified
     *
     * @param gmtModified the value for text_tag.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_tag.user_id
     *
     * @return the value of text_tag.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_tag.user_id
     *
     * @param userId the value for text_tag.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_tag.tag_name
     *
     * @return the value of text_tag.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_tag.tag_name
     *
     * @param tagName the value for text_tag.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_tag.text_id_list
     *
     * @return the value of text_tag.text_id_list
     *
     * @mbggenerated
     */
    public String getTextIdList() {
        return textIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_tag.text_id_list
     *
     * @param textIdList the value for text_tag.text_id_list
     *
     * @mbggenerated
     */
    public void setTextIdList(String textIdList) {
        this.textIdList = textIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_tag.env
     *
     * @return the value of text_tag.env
     *
     * @mbggenerated
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_tag.env
     *
     * @param env the value for text_tag.env
     *
     * @mbggenerated
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }
}