package com.xxs.json.entity;

import lombok.*;

import java.io.Serializable;
import java.util.Date;
@Data
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class TextLabel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.label_name
     *
     * @mbggenerated
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.label_type
     *
     * @mbggenerated
     */
    private Byte labelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.label_father
     *
     * @mbggenerated
     */
    private Long labelFather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.env
     *
     * @mbggenerated
     */
    private String env;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_label.tag_id_list
     *
     * @mbggenerated
     */
    private String tagIdList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table text_label
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.id
     *
     * @return the value of text_label.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.id
     *
     * @param id the value for text_label.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.gmt_create
     *
     * @return the value of text_label.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.gmt_create
     *
     * @param gmtCreate the value for text_label.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.gmt_modified
     *
     * @return the value of text_label.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.gmt_modified
     *
     * @param gmtModified the value for text_label.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.user_id
     *
     * @return the value of text_label.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.user_id
     *
     * @param userId the value for text_label.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.label_name
     *
     * @return the value of text_label.label_name
     *
     * @mbggenerated
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.label_name
     *
     * @param labelName the value for text_label.label_name
     *
     * @mbggenerated
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.label_type
     *
     * @return the value of text_label.label_type
     *
     * @mbggenerated
     */
    public Byte getLabelType() {
        return labelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.label_type
     *
     * @param labelType the value for text_label.label_type
     *
     * @mbggenerated
     */
    public void setLabelType(Byte labelType) {
        this.labelType = labelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.label_father
     *
     * @return the value of text_label.label_father
     *
     * @mbggenerated
     */
    public Long getLabelFather() {
        return labelFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.label_father
     *
     * @param labelFather the value for text_label.label_father
     *
     * @mbggenerated
     */
    public void setLabelFather(Long labelFather) {
        this.labelFather = labelFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.env
     *
     * @return the value of text_label.env
     *
     * @mbggenerated
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.env
     *
     * @param env the value for text_label.env
     *
     * @mbggenerated
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_label.tag_id_list
     *
     * @return the value of text_label.tag_id_list
     *
     * @mbggenerated
     */
    public String getTagIdList() {
        return tagIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_label.tag_id_list
     *
     * @param tagIdList the value for text_label.tag_id_list
     *
     * @mbggenerated
     */
    public void setTagIdList(String tagIdList) {
        this.tagIdList = tagIdList;
    }
}