package com.xxs.json.mapper;

import com.xxs.json.entity.BaseManager;
import com.xxs.json.entity.BaseManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int countByExample(BaseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int deleteByExample(BaseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int insert(BaseManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int insertSelective(BaseManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    List<BaseManager> selectByExample(BaseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    BaseManager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseManager record, @Param("example") BaseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseManager record, @Param("example") BaseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseManager record);
}