package com.xxs.json.mapper;

import com.xxs.json.entity.BaseConfig;
import com.xxs.json.entity.BaseConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int countByExample(BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int deleteByExample(BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int insert(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int insertSelective(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    List<BaseConfig> selectByExampleWithBLOBs(BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    List<BaseConfig> selectByExample(BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    BaseConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseConfig record, @Param("example") BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BaseConfig record, @Param("example") BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseConfig record, @Param("example") BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseConfig record);
}