package com.xxs.json.mapper;

import com.xxs.json.entity.RequestLog;
import com.xxs.json.entity.RequestLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int countByExample(RequestLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int deleteByExample(RequestLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int insert(RequestLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int insertSelective(RequestLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    List<RequestLog> selectByExample(RequestLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    RequestLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RequestLog record, @Param("example") RequestLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RequestLog record, @Param("example") RequestLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RequestLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RequestLog record);
}