package com.xxs.json.mapper;

import com.xxs.json.entity.TextBody;
import com.xxs.json.entity.TextBodyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TextBodyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int countByExample(TextBodyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int deleteByExample(TextBodyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int insert(TextBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int insertSelective(TextBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    List<TextBody> selectByExample(TextBodyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    TextBody selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TextBody record, @Param("example") TextBodyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TextBody record, @Param("example") TextBodyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TextBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_body
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TextBody record);
}